name: 'Terraform Deployment'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash

env: 
  ROOT_PATH: '${{ github.workspace }}/scr'


jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Terraform init -upgrade
        run: terraform init
        working-directory: ${{ env.ROOT_PATH }}
  
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        
      - name: Terraform destroy
        run: terraform destroy -auto-approve

      # - name: Terraform Destroy 
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        # run: terraform destroy -auto-approve  
